# CursorBeam Setup Script
# Quick installation and configuration

param(
    [switch]$SkipInstall,
    [switch]$Start
)

$ErrorActionPreference = "Stop"

function Write-Header {
    param([string]$Text)
    Write-Host ""
    Write-Host "═══════════════════════════════════════════════" -ForegroundColor Cyan
    Write-Host "  $Text" -ForegroundColor White
    Write-Host "═══════════════════════════════════════════════" -ForegroundColor Cyan
    Write-Host ""
}

function Write-Success {
    param([string]$Text)
    Write-Host "✓ $Text" -ForegroundColor Green
}

function Write-Info {
    param([string]$Text)
    Write-Host "→ $Text" -ForegroundColor Yellow
}

function Write-Error2 {
    param([string]$Text)
    Write-Host "✗ $Text" -ForegroundColor Red
}

Clear-Host
Write-Header "CursorBeam - Quick Setup"

# Check Node.js
Write-Info "Checking prerequisites..."
try {
    $nodeVersion = node --version
    Write-Success "Node.js $nodeVersion"
} catch {
    Write-Error2 "Node.js not found!"
    Write-Host "`nPlease install Node.js from: https://nodejs.org/" -ForegroundColor Yellow
    Write-Host "After installation, restart PowerShell and run setup again." -ForegroundColor Yellow
    Read-Host "`nPress Enter to exit"
    exit 1
}

try {
    $npmVersion = npm --version
    Write-Success "npm $npmVersion"
} catch {
    Write-Error2 "npm not found!"
    Read-Host "`nPress Enter to exit"
    exit 1
}

# Install dependencies
if (-not $SkipInstall) {
    Write-Header "Installing Dependencies"
    Write-Info "Running npm install (this may take a minute)..."
    npm install
    if ($LASTEXITCODE -eq 0) {
        Write-Success "Dependencies installed successfully"
    } else {
        Write-Error2 "Failed to install dependencies"
        Read-Host "`nPress Enter to exit"
        exit 1
    }
} else {
    Write-Info "Skipping dependency installation (--SkipInstall flag)"
}

# Configuration
$envPath = Join-Path $PSScriptRoot ".env"
$envExamplePath = Join-Path $PSScriptRoot ".env.example"

Write-Header "Configuration"

if (-not (Test-Path $envPath)) {
    Write-Info "Creating configuration file..."
    
    # Generate random password
    $password = -join ((65..90) + (97..122) + (48..57) | Get-Random -Count 16 | ForEach-Object {[char]$_})
    
    # Detect Cursor path
    $cursorPath = "$env:LOCALAPPDATA\Programs\cursor\Cursor.exe"
    if (-not (Test-Path $cursorPath)) {
        # Try alternative locations
        $altPaths = @(
            "$env:PROGRAMFILES\Cursor\Cursor.exe",
            "$env:PROGRAMFILES(X86)\Cursor\Cursor.exe"
        )
        $found = $false
        foreach ($path in $altPaths) {
            if (Test-Path $path) {
                $cursorPath = $path
                $found = $true
                break
            }
        }
        
        if (-not $found) {
            Write-Info "Cursor.exe not found at default location"
            Write-Host "`nPlease enter your Cursor.exe path:" -ForegroundColor Yellow
            Write-Host "(or press Enter to set it later in .env file)" -ForegroundColor Gray
            $userPath = Read-Host "`nPath"
            if ($userPath) {
                $cursorPath = $userPath.Trim('"')
            } else {
                $cursorPath = "C:\Path\To\Cursor.exe"
            }
        }
    } else {
        Write-Success "Cursor found at: $cursorPath"
    }
    
    # Create .env
    $envContent = @"
# CursorBeam Configuration
# Generated by setup.ps1 on $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")

# Password for PWA login (automatically generated)
# Save this password - you'll need it to connect from your phone!
PASSWORD=$password

# Cursor executable path
CURSOR_EXE=$cursorPath

# Server port (default: 9800)
PORT=9800

# Chrome DevTools Protocol port (default: 9222)
CDP_PORT=9222

# Optional: Project root directory for switching projects
# Uncomment and set your projects folder path:
# PROJECTS_ROOT=C:\Users\YourName\projects

# Optional: Polling interval in milliseconds (default: 1500)
# Lower = more responsive, Higher = less CPU usage
# POLL_MS=1500
"@
    
    Set-Content -Path $envPath -Value $envContent -Encoding UTF8
    Write-Success ".env file created"
    
    Write-Host ""
    Write-Host "═══════════════════════════════════════════════" -ForegroundColor Green
    Write-Host "  YOUR LOGIN PASSWORD" -ForegroundColor White
    Write-Host "═══════════════════════════════════════════════" -ForegroundColor Green
    Write-Host ""
    Write-Host "  $password" -ForegroundColor Yellow
    Write-Host ""
    Write-Host "Save this password! You'll need it to login from your phone." -ForegroundColor Cyan
    Write-Host ""
    Write-Host "Press any key to continue..." -ForegroundColor Gray
    $null = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
} else {
    Write-Success ".env file already exists"
    Write-Info "To regenerate config, delete .env and run setup again"
}

# Network Information
Write-Header "Network Information"

Write-Info "Detecting network addresses..."

try {
    $localIp = (Get-NetIPAddress -AddressFamily IPv4 | Where-Object {
        $_.InterfaceAlias -notlike "*Loopback*" -and 
        $_.InterfaceAlias -notlike "*VMware*" -and 
        $_.InterfaceAlias -notlike "*VirtualBox*" -and
        ($_.PrefixOrigin -eq "Dhcp" -or $_.PrefixOrigin -eq "Manual")
    } | Select-Object -First 1).IPAddress
    
    if ($localIp) {
        Write-Success "Local Network IP: $localIp"
        Write-Host ""
        Write-Host "Connect from your phone (same WiFi):" -ForegroundColor Cyan
        Write-Host "  http://$($localIp):9800" -ForegroundColor Yellow
        Write-Host ""
    } else {
        Write-Info "Could not auto-detect local IP"
        Write-Host "Run 'ipconfig' to find your local IP address" -ForegroundColor Gray
    }
} catch {
    Write-Info "Network detection skipped"
}

# Check for Tailscale
try {
    $tailscaleCmd = Get-Command tailscale -ErrorAction SilentlyContinue
    if ($tailscaleCmd) {
        $tailscaleIp = (tailscale ip -4 2>$null) | Select-Object -First 1
        if ($tailscaleIp) {
            Write-Success "Tailscale IP: $tailscaleIp"
            Write-Host ""
            Write-Host "Connect from anywhere (Tailscale VPN):" -ForegroundColor Cyan
            Write-Host "  http://$($tailscaleIp):9800" -ForegroundColor Yellow
            Write-Host ""
            Write-Host "Install Tailscale on your phone to use this address." -ForegroundColor Gray
            Write-Host ""
        }
    } else {
        Write-Info "Tailscale not detected (optional - for remote access)"
        Write-Host "Install from: https://tailscale.com/download" -ForegroundColor Gray
    }
} catch {
    # Tailscale not installed, skip silently
}

# Completion
Write-Header "Setup Complete!"

Write-Host "What's next?" -ForegroundColor Cyan
Write-Host ""
Write-Host "1. Start the server:" -ForegroundColor White
Write-Host "   npm start" -ForegroundColor Yellow
Write-Host ""
Write-Host "2. Open the URL on your phone (shown above)" -ForegroundColor White
Write-Host ""
Write-Host "3. Login with your password" -ForegroundColor White
Write-Host ""
Write-Host "4. Optional: Install as PWA (Add to Home Screen)" -ForegroundColor White
Write-Host ""
Write-Host "Need help? Check:" -ForegroundColor Gray
Write-Host "  • README.md - Project overview" -ForegroundColor Gray
Write-Host "  • INSTALL.md - Detailed setup" -ForegroundColor Gray
Write-Host "  • TROUBLESHOOTING.md - Problem solving" -ForegroundColor Gray
Write-Host ""

if ($Start) {
    Write-Info "Starting server (--Start flag provided)..."
    npm start
}
