# Cursor Mobile Setup Script
# One-click installation and configuration

param(
    [switch]$SkipInstall,
    [switch]$Start
)

$ErrorActionPreference = "Stop"

function Write-Header {
    param([string]$Text)
    Write-Host ""
    Write-Host "═══════════════════════════════════════════════" -ForegroundColor Cyan
    Write-Host "  $Text" -ForegroundColor White
    Write-Host "═══════════════════════════════════════════════" -ForegroundColor Cyan
    Write-Host ""
}

function Write-Success {
    param([string]$Text)
    Write-Host "✓ $Text" -ForegroundColor Green
}

function Write-Info {
    param([string]$Text)
    Write-Host "→ $Text" -ForegroundColor Yellow
}

function Write-Error2 {
    param([string]$Text)
    Write-Host "✗ $Text" -ForegroundColor Red
}

Clear-Host
Write-Header "Cursor Mobile - Setup"

# Check Node.js
Write-Info "Checking Node.js..."
try {
    $nodeVersion = node --version
    Write-Success "Node.js found: $nodeVersion"
} catch {
    Write-Error2 "Node.js not found!"
    Write-Host "Please install Node.js from: https://nodejs.org/" -ForegroundColor Yellow
    exit 1
}

# Check npm
Write-Info "Checking npm..."
try {
    $npmVersion = npm --version
    Write-Success "npm found: $npmVersion"
} catch {
    Write-Error2 "npm not found!"
    exit 1
}

# Install dependencies
if (-not $SkipInstall) {
    Write-Header "Installing Dependencies"
    Write-Info "Running npm install..."
    npm install
    if ($LASTEXITCODE -eq 0) {
        Write-Success "Dependencies installed successfully"
    } else {
        Write-Error2 "Failed to install dependencies"
        exit 1
    }
} else {
    Write-Info "Skipping dependency installation (--SkipInstall)"
}

# Check if .env exists
$envPath = Join-Path $PSScriptRoot ".env"
$envExamplePath = Join-Path $PSScriptRoot ".env.example"

Write-Header "Configuration"

if (-not (Test-Path $envPath)) {
    Write-Info "Creating .env file..."
    
    # Generate random password
    $password = -join ((65..90) + (97..122) + (48..57) | Get-Random -Count 16 | ForEach-Object {[char]$_})
    
    # Detect Cursor path
    $cursorPath = "$env:LOCALAPPDATA\Programs\cursor\Cursor.exe"
    if (-not (Test-Path $cursorPath)) {
        Write-Info "Cursor not found at default location"
        Write-Host "Please enter your Cursor.exe path (or press Enter to skip):" -ForegroundColor Yellow
        $userPath = Read-Host
        if ($userPath) {
            $cursorPath = $userPath
        }
    } else {
        Write-Success "Cursor found at: $cursorPath"
    }
    
    # Create .env
    $envContent = @"
# Cursor Mobile Configuration
# Generated by setup.ps1 on $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")

# Password for PWA login (automatically generated)
V2_PASSWORD=$password

# Cursor executable path
V2_CURSOR_EXE=$cursorPath

# Ports (default values, change if needed)
V2_PORT=9800
V2_CDP_PORT=9222

# Optional: Project root for switching projects
# V2_PROJECTS_ROOT=C:\Users\YourName\projects

# Optional: Polling interval in milliseconds (default: 1500)
# V2_POLL_MS=1500
"@
    
    Set-Content -Path $envPath -Value $envContent -Encoding UTF8
    Write-Success ".env file created"
    Write-Host ""
    Write-Host "═══════════════════════════════════════════════" -ForegroundColor Green
    Write-Host "  YOUR LOGIN PASSWORD:" -ForegroundColor White
    Write-Host "  $password" -ForegroundColor Yellow
    Write-Host "═══════════════════════════════════════════════" -ForegroundColor Green
    Write-Host ""
    Write-Host "Save this password! You'll need it to connect from your phone." -ForegroundColor Yellow
    Write-Host "Press any key to continue..."
    $null = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
} else {
    Write-Success ".env file already exists"
    Write-Info "If you need to regenerate it, delete .env and run setup again"
}

# Get network info
Write-Header "Network Information"

try {
    $localIp = (Get-NetIPAddress -AddressFamily IPv4 | Where-Object {
        $_.InterfaceAlias -notlike "*Loopback*" -and 
        $_.InterfaceAlias -notlike "*VMware*" -and 
        $_.InterfaceAlias -notlike "*VirtualBox*" -and
        $_.PrefixOrigin -eq "Dhcp" -or $_.PrefixOrigin -eq "Manual"
    } | Select-Object -First 1).IPAddress
    
    if ($localIp) {
        Write-Success "Local IP: $localIp"
        Write-Host ""
        Write-Host "Connect from your phone using:" -ForegroundColor Cyan
        Write-Host "  http://$($localIp):9800" -ForegroundColor Yellow
    } else {
        Write-Info "Could not detect local IP automatically"
    }
} catch {
    Write-Info "Could not detect network configuration"
}

# Check for Tailscale
try {
    $tailscaleExe = Get-Command tailscale -ErrorAction SilentlyContinue
    if ($tailscaleExe) {
        $tailscaleIp = (tailscale ip -4 2>$null) | Select-Object -First 1
        if ($tailscaleIp) {
            Write-Success "Tailscale IP: $tailscaleIp"
            Write-Host "  http://$($tailscaleIp):9800" -ForegroundColor Yellow
        }
    }
} catch {
    # Tailscale not installed, skip
}

Write-Header "Setup Complete!"

Write-Host "Next steps:" -ForegroundColor Cyan
Write-Host ""
Write-Host "1. Start the server:" -ForegroundColor White
Write-Host "   npm run v2:start" -ForegroundColor Yellow
Write-Host ""
Write-Host "2. Open the URL on your phone" -ForegroundColor White
Write-Host ""
Write-Host "3. Login with your generated password" -ForegroundColor White
Write-Host ""
Write-Host "For more information, see README.md" -ForegroundColor Gray
Write-Host ""

if ($Start) {
    Write-Info "Starting server (--Start flag)..."
    npm run v2:start
}
