/**
 * Installs the Cursor Remote Supervisor to run automatically on Windows login.
 * Creates a silent .vbs script in the user's Startup folder.
 * 
 * Run: npx tsx v2/install-autostart.ts
 */

import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(__dirname, '..');

const startupDir = path.join(
  os.homedir(),
  'AppData', 'Roaming', 'Microsoft', 'Windows', 'Start Menu', 'Programs', 'Startup'
);

const vbsContent = `
' Cursor Remote Supervisor Autostart
' Generated by v2/install-autostart.ts

Set WshShell = CreateObject("WScript.Shell")
' Run supervisor silently (window style 0)
WshShell.Run "cmd /c cd /d """ & "${rootDir}" & """ && npx tsx v2/supervisor.ts", 0, False
`;

const vbsPath = path.join(startupDir, 'CursorRemoteSupervisor.vbs');

try {
  fs.writeFileSync(vbsPath, vbsContent.trim());
  console.log('');
  console.log('✅ Successfully installed Supervisor autostart!');
  console.log('   File created: ' + vbsPath);
  console.log('');
  console.log('   The supervisor will now start automatically whenever you log into Windows.');
  console.log('   It runs silently in the background on port 9799.');
  console.log('');
  console.log('   To test it right now without restarting, run:');
  console.log('   npx tsx v2/supervisor.ts');
  console.log('');
  console.log('   Then open your phone browser to:');
  console.log('   http://<your-tailscale-ip>:9799');
  console.log('');
} catch (e) {
  console.error('❌ Failed to create autostart script:', e);
}
